/*
 * BreweryX Bukkit-Plugin for an alternate brewing process
 * Copyright (C) 2024 The Brewery Team
 *
 * This file is part of BreweryX.
 *
 * BreweryX is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * BreweryX is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with BreweryX. If not, see <http://www.gnu.org/licenses/gpl-3.0.html>.
 */

package com.dre.brewery.lore;

import com.dre.brewery.utility.Logging;
import org.jetbrains.annotations.NotNull;

import java.io.FilterInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.security.InvalidKeyException;
import java.util.List;

/**
 * A Scramble Stream that uses XOR operations to unscramble an inputstream.
 * <p>a byte generator feeded with the seed is used as xor source
 * <p>Used to unscramble data generated by the XORScrambleStream
 */
public final class XORUnscrambleStream extends FilterInputStream {

    private final List<Long> prevSeeds;
    private long seed;
    private SeedInputStream xorStream;
    private boolean running;
    private boolean markRunning;
    private boolean markxor;

    private SuccessType successType = SuccessType.NONE;

    /**
     * Create a new instance of an XORUnscrambler, unscrambling the given inputstream.
     *
     * @param in   The Inputstream to be unscrambled
     * @param seed The seed used for unscrambling
     */
    public XORUnscrambleStream(final InputStream in, final long seed) {
        super(in);
        this.seed = seed;
        this.prevSeeds = null;
    }

    /**
     * Create a new instance of an XORUnscrambler, unscrambling the given inputstream.
     * <p>If given a List of previous Seeds, the unscrambler will try all of them for unscrambling the stream in case the seed fails.
     *
     * @param in        The Inputstream to be unscrambled
     * @param seed      The seed used for unscrambling
     * @param prevSeeds List of previously used seeds
     */
    public XORUnscrambleStream(final InputStream in, final long seed, final List<Long> prevSeeds) {
        super(in);
        this.seed = seed;
        this.prevSeeds = prevSeeds;
    }

    /**
     * Before unscrambling, this has to be called to tell the unscrambler that scrambled data will follow.
     * <br>Before starting the unscrambler, any data will just be passed through unmodified to the underlying stream.
     * <br>The Unscrambling can be started and stopped arbitrarily at any point, allowing for parts of already unscrambled data in the stream.
     *
     * @throws IOException         IOException
     * @throws InvalidKeyException If the scrambled data could not be read, very likely caused by a wrong seed. Thrown after checking all previous seeds.
     */
    public final void start() throws IOException, InvalidKeyException {
        this.running = true;
        if (this.xorStream == null) {
            final var id = (short) (this.in.read() << 8 | this.in.read());
            if (id == 0) {
                this.running = false;
                this.successType = SuccessType.UNSCRAMBLED;
                Logging.debugLog("Unscrambled data");
                return;
            }
            final var parity = this.in.read();
            this.xorStream = new SeedInputStream(this.seed ^ id);
            var success = this.checkParity(parity);
            if (success) {
                this.successType = SuccessType.MAIN_SEED;
                Logging.debugLog("Using main Seed to unscramble");
            }

            if (!success && this.prevSeeds != null) {
                for (var i = this.prevSeeds.size() - 1; i >= 0; i--) {
                    this.seed = this.prevSeeds.get(i);
                    this.xorStream = new SeedInputStream(this.seed ^ id);
                    if (success = this.checkParity(parity)) {
                        this.successType = SuccessType.PREV_SEED;
                        Logging.debugLog("Had to use prevSeed to unscramble");
                        break;
                    }
                }
            }
            if (!success) {
                throw new InvalidKeyException("Could not read scrambled data, is the seed wrong?");
            }
        }
    }

    private boolean checkParity(final int parity) {
        return ((parity ^ this.xorStream.read()) & 0xFF) == ((int) (this.seed >> 48) & 0xFF); // Parity/Sanity
    }

    /**
     * Stop the unscrambling, any following data will be passed through unmodified.
     * <p>The unscrambling can be started again at any point after calling this
     */
    public void stop() {
        this.running = false;
    }

    @Override
    public final int read() throws IOException {
        if (!this.running) {
            return this.in.read();
        }
        return (this.in.read() ^ this.xorStream.read()) & 0xFF;
    }

    @Override
    public final int read(@NotNull final byte[] b, final int off, int len) throws IOException {
        if (!this.running) {
            return this.in.read(b, off, len);
        }
        len = this.in.read(b, off, len);
        for (var i = off; i < len + off; i++) {
            b[i] ^= this.xorStream.read();
        }
        return len;
    }

    /**
     * What was used to unscramble the stream: it was already unscrambled | Main Seed | Prev Seed
     *
     * @return The Type of Seed used to unscramble this, if any
     */
    public final SuccessType getSuccessType() {
        return this.successType;
    }

    @SuppressWarnings("ResultOfMethodCallIgnored")
    @Override
    public final long skip(final long n) throws IOException {
        final var skipped = this.in.skip(n);
        if (this.running && skipped > 0) {
            this.xorStream.skip(skipped);
        }
        return skipped;
    }

    @Override
    public final void close() throws IOException {
        if (this.xorStream != null) {
            this.xorStream.close();
            this.xorStream = null;
        }
        this.running = false;
        super.close();
    }

    @Override
    public final boolean markSupported() {
        return this.in.markSupported();
    }

    @Override
    public final synchronized void reset() throws IOException {
        this.in.reset();
        if (this.markxor) {
            this.xorStream.reset();
        } else {
            this.xorStream = null;
        }
        this.running = this.markRunning;
    }

    @Override
    public final synchronized void mark(final int readlimit) {
        this.in.mark(readlimit);
        if (this.xorStream != null) {
            this.xorStream.mark(readlimit);
            this.markxor = true;
        }
        this.markRunning = this.running;
    }

    /**
     * What succeeded in unscrambling the Stream.
     */
    public enum SuccessType {
        /**
         * The Stream was already unscrambled.
         */
        UNSCRAMBLED,

        /**
         * The Main Seed was used to unscramble the Stream.
         */
        MAIN_SEED,

        /**
         * One of the Previous Seeds was used to unscramble the Stream.
         */
        PREV_SEED,

        /**
         * It was not successful.
         */
        NONE
    }
}
